version: 1.0
author:
description:
os: unix
modules:
  - extract_uac.yml
  - utmp.yml
version: 1.0
author:
description:
os: unix
modules:
  - extract_uac.yml
  - audit.yml
  - bodyfile.yml
  - boot.yml
  - cron.yml
  - debug.yml
  - dpkg.yml
  - journal.yml
  - kernel.yml
  - lastlog.yml
  - mail.yml
  - message.yml
  - postgresql.yml
  - syslog.yml  
  - utmp.yml
  - yum.yml
  - arp.yml
  - blkid.yml
  - df.yml
  - dmidecode.yml
  - dpkg-l.yml
  - env.yml
  - findmnt.yml
  - free.yml
  - ip_route.yml
  - iptables.yml
  - last.yml
  - lsblk.yml
  - lsmod.yml
  - lsusb.yml
  - mount.yml
  - netstat.yml
  - ps.yml
  - sysctl.yml
  - systemctlluf.yml
  - top.yml
  - vmstat.yml